using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HospitalManagementSystem.Model
{
    public class Patient
    {
        public int PatientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }

        public string password { get; set; }

        public ICollection<Appointment> Appointments { get; set; }

        // Constructor without PatientID (auto-generated by DB)
        public Patient(string firstName, string lastName, DateTime dateOfBirth, string gender,
                       string contactNumber, string email, string address, string password)
        {
            FirstName = firstName;
            LastName = lastName;
            DateOfBirth = dateOfBirth;
            Gender = gender;
            ContactNumber = contactNumber;
            Email = email;
            Address = address;
            this.password = password;
            Appointments = new List<Appointment>();
        }

        // Optional: parameterless constructor (required for some serialization/deserialization tools)
        public Patient() { }
    }
}
